### ISSUE TITLE
Openshift dynamic fsGroup

### ISSUE THREAD

**Issue by yaroslavkasatikov** [bank-vaults/bank-vaults#1027]
Hello team,

Could you please add dynamic fsGroup for openshift to operator? As far as you know, Openshift UID /fsGroup ranges are dynamic so if you set empty value for fsGroup it will be selected from range.

But I can't create the STS without fsGroup value because if value for fsGroup is empty, it will be 1000 in stateful set, so I need to create special SCC where fsGroup1000 is allowed.

For example it can be realized with addtitonal boolean variable ( something like  openshift=true). If it is set to true, the securityContext for STS template will be empty. Certainly it may be implemented in other way, but it will be very useful for Openshift users.

**Comment by bonifaido** [comment]
Hi @yaroslavkasatikov,

if you check to specification of the `fsGroup` value only happens if you don't specify a `securityContext`, you can give one in the Vault spec, and leave fsGroup empty in it.

**Comment by yaroslavkasatikov** [comment]
Hi team,
sorry, for great delay in respond.
I was sure all works fine with 

```
spect:
  securityContext: {}

```

But it was a mistake and all works because SCC with fsGroup 1000 had been created. but I have migratred vault to new cluster and found that it is still actual.

I tried to perform some test from your example and found that these both configs below don't work:

1)
```
spec:
  securityContext:
    fsGroup: ""
```

2) 
```
spec:
  securityContext:
    fsGroup: {}
```

Both of them lead to this error in operators' log:

```
alpha1.Vault.Spec: v1alpha1.VaultSpec.SecurityContext: v1.PodSecurityContext.FSGroup: readUint64: unexpected character: ▒, error found in #10 byte of ...|fsGroup":""},"servic|..., bigger context ...|":"","resources":{},"securityContext":{"fsGroup":""},"serviceAccount":"vault-vault","serviceMonitorE|...
```

version:

```[testuser@yaroslav vault-advatys]$ helm ls
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
vault-operator  vault-operator  1               2020-07-26 20:32:43.404232367 +0200 CEST        deployed        vault-operator-1.3.5    1.3.3
```

**Comment by aelbarkani** [comment]
FYI, I've tested several configs in OpenShift. The only one that seems to be working is this one:
```
          securityContext: 
            runAsNonRoot: true
```

**Comment by csatib02** [comment]
Closing this, as a solution was found, if someone needs further assistance will reopen!
