### ISSUE TITLE
[vault-secrets-webhook] sync secrets/configmaps with vault secrets

### ISSUE THREAD

**Issue by claas-fridtjof-lisowski** [bank-vaults/bank-vaults#1251]
**Is your feature request related to a problem? Please describe.**
We create secrets and CRs with secrets from vault as described [here](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/configuration/#mutate-data-from-vault-and-replace-it-in-kubernetes-secret). That works well so far. However when the secret in vault updates we have to re-apply the resource so that the updated secret is present in the secret/CR.

**Describe the solution you'd like**
It would be great to have a feature that monitors the mutated secrets corresponding vault path. If the secret in vault changes then update it in the namespace. (or does something like this already exist, maybe there is also another workaround present?)

**Describe alternatives you've considered**
So far we re-apply resources via a pipeline. that works fine.

**Additional context**
Moving on to a GitOps (Argo CD) way the workaround to apply resources won't work. Since the data for the secret in k8s is mutated and doesn't match the data in the resource located in the git repo we need to exclude it to be compared.

We could have a sync less frequent, e.g. of 2x day and run a pre-sync-job which deletes all resources which have been mutated and then it will be applied via Argo CD again but that is not really what we want to do (though a possible workaround for the time being)

**Comment by Elyytscha** [comment]
we tried to use:
https://argoproj.github.io/argo-cd/user-guide/compare-options/

but this feature seems not working:
https://github.com/argoproj/argo-cd/issues/7011

**Comment by bonifaido** [comment]
I totally feel what you say here, for this we would need a separate operator pattern application that runs inside the webhook process (most probably that would be the best). In case of Secrets/ConfigMaps/etc. (non-pod) resouseces the webhook's ServiceAccount is used to authenticate against Vault, so this would be the best place to monitor Vault as well here.

**Comment by dkulchinsky** [comment]
@claas-fridtjof-lisowski check out https://github.com/tuenti/secrets-manager

**Comment by claas-fridtjof-lisowski** [comment]
@dkulchinsky thanks for that link. Do you use it? From what I now saw is that it doesn't really have a good RBAC/policy control per secret but the complete deployment is configured to use either approle or kubernetes auth. That doesn't work so well on a cluster shared with x other teams.
We might probably use sealed secrets and get those static secrets we need from Vault and write them into a sealed secret yaml. We don't use custom resources (any longer) with secrets and I think configmaps work fine with the GitOps approach because they are mounted to the pod and only then get mutated.

**Comment by notjames** [comment]
> I totally feel what you say here, for this we would need a separate operator pattern application that runs inside the webhook process (most probably that would be the best). In case of Secrets/ConfigMaps/etc. (non-pod) resouseces the webhook's ServiceAccount is used to authenticate against Vault, so this would be the best place to monitor Vault as well here.

@bonifaido is there any chance someone has/will add this feature? We just ran into this as a problem as well.
