### ISSUE TITLE
skip unparsable HCL in externalConfigs and continue instead of terminating config updates

### ISSUE THREAD

**Issue by jkirkham-ratehub** [bank-vaults/bank-vaults#1254]
**Is your feature request related to a problem? Please describe.**

A co-worker accidentally left a single quote character out of a policy definition.  The HCL parser of course failed, but this terminated all parsing of the externalConfig policies section.

**Describe the solution you'd like**
Since each policy `rule` represents a parsable HCL block, it would be preferable to to log the error and continue with the next rule instead of returning an error and skipping all other rule blocks.
https://github.com/banzaicloud/bank-vaults/blob/master/internal/vault/operator_client.go#L825
This likely applies similarly to other externalConfig settings like auth.

**Describe alternatives you've considered**
I've considered creating a config-checker that would run in our CI pipeline and validate the externalConfigs before they could be applied to the vault instance.  (I may do this anyway since getting that feedback before the config changes are applied is a good practice).

**Additional context**
This is using the latest version of the vault-operator installed from the Helm chart v1.11.1

**Comment by bonifaido** [comment]
This is a good idea, however, it would maybe break current functionality, I'm not sure. But tbh, I'm okay with continuing to the next config section in an error case.
