### ISSUE TITLE
Migrate from Standard Vault to Bank-Vaults

### ISSUE THREAD

**Issue by Xtigyro** [bank-vaults/bank-vaults#1264]
Hey guys - thank you very much for this inspiring project! 👋 

I would like to ask whether it's possible and there's some documentation (couldn't find it) to migrate to your Vault Operator from a standard Vault instance deployed thru the [official Helm chart](https://github.com/hashicorp/vault-helm).

In my particular case - using Amazon DynamoDB for the storage and AWS KMS for the auto-unsealing. Obviously, my Root token and Recovery keys (yes, not Unseal keys) are NOT on AWS S3.

Or is the only way thru the [operator migrate](https://www.vaultproject.io/docs/commands/operator/migrate)? Still the keys and root token won't be on AWS S3 though.

**Comment by bonifaido** [comment]
Hi @Xtigyro, thanks! :)

unseal with Vault itself (using the `seal` stanza) is supported as well with the operator, as you can see in this GCP example: https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-gcs-ha-autounseal.yaml#L35

The data doesn't have to be migrated, you can use the DynamoDB backend with the operator as well (for the operator it doesn't matter which Vault storage backend are you using), so the `operator migrate` subcommand is not necessary.

The only thing you need to do is to copy the root-token to a location that the operator can understand (AWS S3 for example, encrypted with KMS). Please see https://banzaicloud.com/docs/bank-vaults/unseal-keys/ for more details.
