### ISSUE TITLE
vault-operator pod stability when watching all namespaces

### ISSUE THREAD

**Issue by maratsal** [bank-vaults/bank-vaults#1288]
vault-operator unstable and fails with log messages attached to the case. I am using helm charts version 1.10.1 for deployment.

**Expected behaviour**:
I would expect it working.

**Steps to reproduce the bug**:
install it in with option to watch all namespaces.

**Additional context**:
When I run it with watching single namespace I don't have any problems.
What I noticed additionally memory usage goes really high. it starts with around 700MB and goes up to 6GB

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.15.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): local k8s deployment
- bank-vaults version (e.g. 0.4.17): 1.10.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): attached
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: attached.
[helm-override.txt](https://github.com/banzaicloud/bank-vaults/files/6240043/helm-override.txt)

[vault-operator.txt](https://github.com/banzaicloud/bank-vaults/files/6240029/vault-operator.txt)

/kind bug

**Comment by maratsal** [comment]
it feels like it is going through all config maps here:
`I0331 23:10:01.148101       1 trace.go:205] Trace[1006933274]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156 (31-Mar-2021 23:08:51.554) (total time: 69593ms):
Trace[1006933274]: [1m9.593713104s] [1m9.593713104s] END
E0331 23:10:01.148177       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 297; INTERNAL_ERROR
I0331 23:14:10.751713       1 trace.go:205] Trace[629431445]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156 (31-Mar-2021 23:10:02.174) (total time: 248576ms):
Trace[629431445]: ---"Objects listed" 248476ms (23:14:00.651)
Trace[629431445]: [4m8.5767814s] [4m8.5767814s] END`

**Comment by maratsal** [comment]
it seems somehow related to slow etcd of k8s.

**Comment by bonifaido** [comment]
How many resources do you have in this cluster for example ConfigMaps and Secrets?

**Comment by maratsal** [comment]
we have around 4000 Config Maps and 1600 secrets and I think the most problem is that configmaps are really heavy as some of them hold helm releases. And in addition to that on that dev cluster we don't have fast etcd.

So from my observation what happens is, operator is trying to fetch all configmaps data to memory (not sure why it needs to collect all of them even) then on some point it is disconnecting from kubernetes api server and starts over (without dumping previous unsuccessful capture). This is causing significant increase in memory usage as each iteration is increasing use memory by about 800MB. 

I could more or less stabilize it by setting memory limit to 6GB as by that several iterations I get lucky and it can fetch all data.

So I would assume there is a room for improvement and not even sure why we are trying to fetch all configmaps from whole cluster.

**Comment by bonifaido** [comment]
4000 ConfigMaps is probably not something that etcd/kubernetes likes, is intended for. I would remove a lot of old releases since helm saves 256 previous revisions by default: https://helm.sh/docs/helm/helm_history/ (I know it is not my business, but anyhow I think chances are quite low that someone will go back 255 releases in release history). I think this is something that could cause issues for other Kubernetes API eating software as well (like other operators).

We use the controller-runtime library underneath which uses caches: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache and it is not something that we have to much control over what it caches I think, and we don't plan to change the library in the near future.

**Comment by maratsal** [comment]
Yes, I know that behaviour of helm and we were using helm 2 and in most of environments tiller was already set to keep only 5 releases (I patched the remaining yesterday to keep only 5).

Why we even need to cache all config maps? What I was thinking is it might be a good idea to work only with namespaces where vault crd is available instead of fetching all config maps?

**Comment by bonifaido** [comment]
I need to look at the code that might something we can fix.
