### ISSUE TITLE
[Helm Vault] Set readOnlyRootFilesystem

### ISSUE THREAD

**Issue by Poweranimal** [bank-vaults/bank-vaults#1351]
**Is your feature request related to a problem? Please describe.**
If one adds a plugin to vault that requires RPC communication between plugin and vault server via Unix socket, the `readOnlyRootFilesystem` must be disabled for the vault container.

See: [Register a new plugin](https://banzaicloud.com/docs/bank-vaults/external-configuration/#register-a-new-plugin)

**Describe the solution you'd like**
An additional flag in the helm chart that allows setting the `readOnlyRootFilesystem`.

**Describe alternatives you've considered**
I haven't found any alternative to come around this issue in the current helm chart.

**Comment by bonifaido** [comment]
I would be more than happy to check out a pull-request for this one! ;)
