### ISSUE TITLE
[vault-secrets-webhook] Can not send signal from sidecar consul-template/vault-agent

### ISSUE THREAD

**Issue by gw0** [bank-vaults/bank-vaults#1364]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
Because dynamic secrets eventually expire it is necessary to rotate them and notify the process to reload the configuration. In the ConfigMap used by the sidecar container `consul-template` (similar for `vault-agent`) one can realize that by providing a `command`, e.g.:

```hcl
template {
  left_delimiter  = "[["
  right_delimiter = "]]"
  error_on_missing_key = true
  contents = <<EOT
[[- with secret "gcp/key/mygcprole" ]]
[[ .Data.private_key_data | base64Decode ]]
[[- end ]]
EOT
  destination = "/vault/secrets/credentials.json"
  command     = "/bin/sh -c \"kill -HUP $(pidof -o %PPID myprocess) || true\""
}
```

Unfortunately, the sidecar `consul-template` is running as user `consul-template` with uid=100 and can not send signals (using kill) to the process `myprocess` running as user `root` with uid=0 in the main container. Attempt to run this from `consul-template` container fail:

```bash
/ $ id
uid=100(consul-template) gid=1000(consul-template) groups=1000(consul-template)
/ $ ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
   19 consul-t  0:00 {docker-entrypoi} /bin/dumb-init /bin/sh /bin/docker-entrypoint.sh -config /vault/c
   24 consul-t  1:22 /bin/consul-template -config=/consul-template/config -config /vault/ct-config/confi
   57 root      2:09 /myprocess
/ $ kill -HUP $(pidof -o %PPID cloud_sql_proxy) || true
sh: can't kill pid 57: Operation not permitted
```

This could be easily solved if there would be an option to specify the `securityContext.runAsUser` field of the sidecar container `consul-template`, e.g.:

```yaml
securityContext:
  runAsUser: 0
```

Unfortunately, the sidecar container `consul-template` is currently running only with:
```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - SYS_PTRACE
```

And in the code https://github.com/banzaicloud/bank-vaults/blob/2b873d189d96e0fdaf5869160ccf95f5abad9963/pkg/webhook/pod.go#L679 there are no options to specify additional values.

**Expected behaviour**:
One would expect that one can configure the `securityContext.runAsUser` setting of the sidecar container `consul-template` (similarly for `vault-agent`). By default it could be even set to 0 to make it always work (although it would degrade the security) or use the same uid as the main container.

**Steps to reproduce the bug**:
Use `vault-secrets-webhook` with the sidecar `consul-template` to render a dynamic secret that needs to be rotated and provide a `command` to send a signal (or kill) the process in the main container.

/kind bug

**Comment by matrix-root** [comment]
Hi! Did you solve that issue?

**Comment by gw0** [comment]
@matrix-root It is still an issue. My workaround to allow sending signals was to run both containers in a Pod as the same user (`securityContext.runAsUser`).
