### ISSUE TITLE
startupSecrets not working with version 2 kv 

### ISSUE THREAD

**Issue by hulucc** [bank-vaults/bank-vaults#1373]
There is not errors in log but kv not actually write to vault. And everything works fine in version 1 kv.

**Comment by bonifaido** [comment]
Can you give us an example what doesn't work especially?

**Comment by hulucc** [comment]
https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-raft.yaml#L181

**Comment by csatib02** [comment]
Hey @hulucc,

It's been a while since you posted this issue, since then a lot of enhancements has been added, please try out the newest version of Bank-Vaults.
If you need further assistance, please raise another ticket.
