### ISSUE TITLE
Autoscaler for vault-secrets webhook?

### ISSUE THREAD

**Issue by andriihrachov** [bank-vaults/bank-vaults#1377]
we have constant problems with admission webhooks failing when there are large rollouts (30-50 pods). The only things that is helping - is to manually scale  vault-secrets-webhook

**Describe the solution you'd like**

Add an optional horizontal pod autoscaler, to handle load

**Describe alternatives you've considered**
Manual scale

**Comment by bonifaido** [comment]
If you have experience with those HPAs already could you please add one to the chart @andriihrachov and we will review it?

**Comment by andriihrachov** [comment]
sure
