### ISSUE TITLE
[vault-secrets-webhook] Running the vault-agent as init-container?

### ISSUE THREAD

**Issue by banschikovde** [bank-vaults/bank-vaults#1450]
Hello!
We have situations where we need to run vault-agent as an init-container.
After reading the official documentation, we did not find such a possibility.

**So I make a request to implement such a feature in vault-secrets-webhook.**

Thank you!

**Comment by spanarek** [comment]
++ very want same solution for consul-template
I.e, if i use consul-template(vault-ct-once), i got similiar behavior:
_I find that banzai has similiar anotation - vault.security.banzaicloud.io/vault-agent-once, but it fits only jobs, when I tried to use it in deployment I had CrashLoopBackOff error (I think this annotation not start container as init)_

**Comment by spanarek** [comment]
Because, i want to use consul-template. 
I'm really looking to resolve this issue. Using consul-template as a sidecar requres exess resources(CPU,RAM for sidecar and addational queries to Vault server)

**Comment by spanarek** [comment]
Finally i found undocumented solution: https://github.com/banzaicloud/bank-vaults/pull/1302/commits/42ab8c6bbb517685d7f07073fe7c1b1447cf2f65
If use two annotations:
`
vault.security.banzaicloud.io/vault-ct-once:` 'true'
vault.security.banzaicloud.io/vault-ct-inject-in-initcontainers: "true" 
`
Consul-template will run as initContainer, render template and exit.
Please append this topic in documentation, thanks!
