### ISSUE TITLE
Secrets retrieved via vault-env-from-path annotation should override the environment variable

### ISSUE THREAD

**Issue by Dylan2010** [bank-vaults/bank-vaults#1455]
This feature request is from this closed bug issue although it is not resolved. 
https://github.com/banzaicloud/bank-vaults/issues/1454

**Is your feature request related to a problem? Please describe.**
when retrieving an environment variable via vault-env-from-path annotation and k8s config map(or secret, env declaration in Deployment) simultaneously, we would see duplicated variables with the same key in the spawning procedure.

**Describe the solution you'd like**
The secret fetched from vault server by the vault-env-from-path should override the one declared in the Deployment which has the same key

**Describe alternatives you've considered**
There should be a precedence for the overriding, it will be ok if the environment defined by deployment/pod/configmap has higher precedence in the spawning process. But currently, we are seeing duplicated environment variables and it is proved that our Dotnet application would choose the two environments randomly when it is running, which is not acceptable. 

**Additional context**
About how to reproduce the issue: 
For a pod running in the cluster, we are using annotation as
vault.security.banzaicloud.io/vault-env-from-path:secret/data/test/vault-demo/la-test
it is retrieving the secrets from the vault server and injecting them into the container's environment. There is a parameter named TestSecret and its value is "la-test-123"

Meanwhile, we also added a block in the Deployment definition to declare an environment variable as
env: - name: TestSecret value: fhquthpdw

When the pod is running, if we kubect exec into it and run /vault/vault-env env, we would see duplicated keys showing inside the spawned process

root@vault-demo-7b7d494b65-lmfzd:/go# /vault/vault-env env |grep TestSecret INFO[0000] received new Vault token addr= app=vault-env path=la-test role=test INFO[0000] initial Vault token arrived app=vault-env INFO[0000] spawning process: [env] app=vault-env TestSecret=fhquthpdw TestSecret=la-test-123 root@vault-demo-7b7d494b65-lmfzd:/go# exit exit

Environment details:

Kubernetes version: 1.19
Cloud-provider/provisioner: EKS
bank-vaults version: 1.14.5
Install method : helm
Logs from the misbehaving component:
INFO[0000] received new Vault token addr= app=vault-env path=la-test role=test
INFO[0000] initial Vault token arrived app=vault-env
INFO[0000] spawning process: [env] app=vault-env
TestSecret=fhquthpdw
TestSecret=la-test-123
Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
I just simplified the deployment definition we are using: apiVersion: apps/v1
kind: Deployment
metadata:
name: vault-demo
namespace: test
spec:
selector:
matchLabels:
app: vault-demo
template:
metadata:
annotations:
vault.security.banzaicloud.io/vault-addr: https://vault.XXX.net
vault.security.banzaicloud.io/vault-env-from-path: secret/data/test/vault-demo/la-test
vault.security.banzaicloud.io/vault-path: la-test
vault.security.banzaicloud.io/vault-role: test
vault.security.banzaicloud.io/vault-tls-secret: vault-tls
containers:
- env:
- name: TestSecret
value: fhquthpdw
envFrom:
- configMapRef:
name: vault-demo
image: somerepo/someiamge:sometag
imagePullPolicy: IfNotPresent
ports:
- containerPort: 9999
protocol: TCP

**Comment by mii-syahid** [comment]
+1
I also have a similar issue , only different case.
In my case, I create 1 deployment in my openshift, with duplicated value of env like below. (without any annotations or special variables defined in special format like; _vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY_ )

```
cat <<EOF | kubectl apply -n mydebugns -f -
oc apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devwebapp-through-service
  labels:
    app: devwebapp-through-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devwebapp-through-service
  template:
    metadata:
      labels:
        app: devwebapp-through-service
    spec:
      containers:
      - name: app
        image: burtlo/devwebapp-ruby:k8s
        imagePullPolicy: Always
        env:
        - name: ELASTIC_IP
          value: "value1"
        - name: ELASTIC_PORT
          value: "value1"
        - name: APP_OVERBOOKING
          value: "value1"
        - name: VAULT_ADDR
          value: "http://external-vault:8002"
        - name: SERVICE_PORT
          value: "8002"
        - name: ELASTIC_IP
          value: "value1"
        - name: ELASTIC_PORT
          value: "value1"
        - name: APP_OVERBOOKING
          value: "value1"
EOF
```

And then I install vaults secret webhook using helm 3:

helm upgrade --namespace vswh --install vswh banzaicloud-stable/vault-secrets-webhook --set securityContext.runAsUser="1001323333" --set debug=true --set REGISTRY_SKIP_VERIFY="true" --set hostNetwork=true --set dnsPolicy=ClusterFirstWithHostNet --set timeoutSeconds=30 --create-namespace

The Openshift Api Logs show an error like below:

```
I0615 10:25:30.465868      20 trace.go:205] Trace[1401542318]: "Call mutating webhook" configuration:vswh-vault-secrets-webhook,webhook:pods.vault-secrets-webhook.admission.banzaicloud.com,resource:/v1, Resource=pods,subresource:,operation:CREATE,UID:a130bdee-2376-42de-a15f-0a1291667e85 (15-Jun-2022 10:25:17.484) (total time: 12981ms):
Trace[1401542318]: [12.981482765s] [12.981482765s] END
W0615 10:25:30.465909      20 dispatcher.go:170] Failed calling webhook, failing open pods.vault-secrets-webhook.admission.banzaicloud.com: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post "https://vswh-vault-secrets-webhook.vswh.svc:443/pods?timeout=30s": context canceled
E0615 10:25:30.465927      20 dispatcher.go:171] failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post "https://vswh-vault-secrets-webhook.vswh.svc:443/pods?timeout=30s": context canceled
E0615 10:25:30.498945      20 fieldmanager.go:191] "[SHOULD NOT HAPPEN] failed to update managedFields" err="failed to convert new object (/v1, Kind=Pod) to smd typed: errors:\n  .spec.containers[name=\"business-logic-nds\"].env: duplicate entries for key [name=\"ELASTIC_PORT\"]\n  .spec.containers[name=\"business-logic-nds\"].env: duplicate entries for key [name=\"ELASTIC_IP\"]\n  .spec.containers[name=\"business-logic-nds\"].env: duplicate entries for key [name=\"APP_OVERBOOKING\"]\n  .spec.containers[name=\"fluentd\"].env: duplicate entries for key [name=\"ELASTIC_PORT\"]\n  .spec.containers[name=\"fluentd\"].env: duplicate entries for key [name=\"ELASTIC_IP\"]\n  .spec.containers[name=\"fluentd\"].env: duplicate entries for key [name=\"APP_OVERBOOKING\"]" VersionKind="/, Kind="

```
