### ISSUE TITLE
better coverage and more reliable secrets mutation needed as race condition exists and mutations fail...

### ISSUE THREAD

**Issue by notjames** [bank-vaults/bank-vaults#1467]
**Is your feature request related to a problem? Please describe.**
We use the vault-secrets-webhook (VSW) heavily in our environment. One problem we are seeing, however, is that if the VSW is not ready then when dependent resources startup and attempt to mutate secrets, if the VSW is not ready then those resources, which are typically either some kind of service or a configmap/secret for a service fail to properly function but the fact that the lack of secrets mutation is a quiet problem which when a service fails requires manual intervention to investigate the problem and secrets mutation failure is often overlooked.

**Describe the solution you'd like**

Could we get better functionality out of the sidecar and out of VSW which could assist in:
1. mitigating the issue of secrets not mutating as a result of lack of readiness in the service or
1. if inability to mutate, some proper output to that fact as a side-car
  1. as a service, vsw should at least expose metrics for secrets failures, attempt, successes, etc
1. it would be nice that the side-car continues to attempt to mutate failed secrets -- most important aspect in my estimation

**Describe alternatives you've considered**
so far the only thing we've come up with is running a script that exec into pods where we use VSW for environmentally stored secrets to validate if secrets mutated by looking through `/proc` -- this is slow and not very reliable.

**Comment by notjames** [comment]
@bonifaido -- thoughts?

**Comment by dwgillies-bluescape** [comment]
+1 Problem just happened again tonight.  our Vault and oauth proxy came up at about the same time an the VSW failed to populate the oath proxy with secrets from vault.

**Comment by bonifaido** [comment]
In the past few months I haven't had the time for the project, but now it is getting focus again, I will try to to look into this in the coming days, I think webhook invocation auto restart tuning and pod disruption budget can help here.

**Comment by notjames** [comment]
/ping @bonifaido -- any progress on this by any chance

**Comment by notjames** [comment]
/ping
I wanted to follow-up on this as it seems to have gone quiet over the last few months.

I'm not sure, actually, if webhook invocation auto restart tuning will work and I'm fairly sure PDBs will not fully work either. The issue is timing of vault-secrets-webhook (VSW) pods readiness in conjunction with vault readiness and lastly, the timing of those two services readiness with those dependent resources that consume VSW. The problem is that you (meaning you, not people in general) will never know the way the world will depend on VSW.

As far as I'm aware, currently, VSW is set up as a set and forget service where dependent resources when created will be detected by VSW by way of annotations and VSW will mutate secrets after one attempt. If that one attempt fails, those dependent resources may never get mutated secrets until manual intervention.

Let's consider the case that @dwgillies-bluescape states above. Due to an unfortunate maintenance requirement, he had to perform a function to fix all the things. One of the components came up before vault did. VSW was not able to mutate secrets because vault wasn't ready. One cannot assume that dependent (on VSW) resources in a cluster will always have vault or VSW available so to mitigate that problem VSW needs to be more resilient such that it should try to mutate secrets if secrets which are supposed to be mutated are not yet mutated.

In the sense of secrets and configmaps, it would be as simple as recognizing whether `/^vault:` (or some variant of this) exists in annotated resources. If it does then VSW should continue to mutate those secrets until either mutation fails after a period of time or mutation occurs. As for ENV mutations, this one is a little more tricky, though I presume that even the `vault-env` binary could potentially do the same "check" though I believe I'm not mistaken that the `vault-env` binary currently performs the mutation setting the environment with mutated secrets, invokes and forks/detaches the application from `entrypoint/cmd` and then exits. If this is the case, that paradigm may have to change. However, one could argue that the application developers could do a better job of detecting mutated secrets and if the mutation fails they exit so that the deployment/rs restarts pods to perform a natural VSW retry. We're starting to employ that type of check in our pods now.

**Comment by notjames** [comment]
A co-worker and I have been discussing the feasibility of forking and submitting a PR. What we're thinking is the best way to approach this is refactoring `vault-env` to validate the response from VSW by checking if the response is valid (tbd) and if it's not (or it's empty) then exit with a non-zero exit status, which should cause pods to go into a `CrashLoopBackOff` state. This would be desirable, in my estimation, however, because if your application requires an env var to contain a mutated secret for runtime, this failure should keep it from running. Arguably, it's better for an application not to run at all when it lacks proper inputs then for it to run at all otherwise -- edge cases likely exist, but the vast majority of times, this is likely the case. We could add annotations to by-pass the new behavior to use the old. 

We also discussed adding an annotation which would be a map of strings `vault-env` could recognize from vault as a bad-state. For instance, in our dev instances, it's not uncommon for developers to create a vault entry with a field value of `fill-me-in`. These kinds of strings could be recognized with the aforementioned annotation.

RFC? cc: @dwgillies-bluescape @bonifaido

**Comment by dwgillies-bluescape** [comment]
We feel like there should be an operational mode in vault-secrets-webhook where if any environment variable contains any of a set of the following regexps after seeding, vault-secrets-webhook should not fork the sub-process but rather, print a list (name1, value1, name2, value2, ...) of the environment variables that match the offending patterns, wait 30-60 seconds, and then restart.

vault_fail_patterns=["vault:.*", "##fill_me_in##", "##fill_me_in_prod##"]

**Comment by squaricdot** [comment]
dockersecrets end up non mutated on the system. kills, seems like like snowballs my vault setup, gitops is also racing with the object and relying on mutationg which then not works. also all automated images use the imagepull secret. so both automation and deployments. and keep harassing vault. deleting the secret and restarting the webhook worked initially.
currently getting rid of vault secrets webhook dealing with docker secrets for all my clusters as all my systems break. and i can only put the webhook as the culprit at this stage as there are 15x more tokens than any other policy. spending already a couple of days on this.

**Comment by notjames** [comment]
> dockersecrets end up non mutated on the system. kills, seems like like snowballs my vault setup, gitops is also racing with the object and relying on mutationg which then not works. also all automated images use the imagepull secret. so both automation and deployments. and keep harassing vault. deleting the secret and restarting the webhook worked initially. currently getting rid of vault secrets webhook dealing with docker secrets for all my clusters as all my systems break. and i can only put the webhook as the culprit at this stage as there are 15x more tokens than any other policy. spending already a couple of days on this.
> 
> webhook should never create non mutated secrets. especially not update earlier mutated secrets with contents of vault refs in etcd. as i understand this ticket is also about.

I'm not sure how you've got VSW set up, but we've never seen the kinds of problems you're describing. It sounds like maybe your setup is in need of some tweaking? Other than a few things we've identified with the ecosystem, it works pretty nicely, but the things we've identified are pretty big deals. The things we spoke of above are one of the main problems we've identified. Another one is the inability for VSW ecosystem to update/mutate secrets in running pods when secrets are changed in vault.

**Comment by squaricdot** [comment]
> > dockersecrets end up non mutated on the system. kills, seems like like snowballs my vault setup, gitops is also racing with the object and relying on mutationg which then not works. also all automated images use the imagepull secret. so both automation and deployments. and keep harassing vault. deleting the secret and restarting the webhook worked initially. currently getting rid of vault secrets webhook dealing with docker secrets for all my clusters as all my systems break. and i can only put the webhook as the culprit at this stage as there are 15x more tokens than any other policy. spending already a couple of days on this.
> > webhook should never create non mutated secrets. especially not update earlier mutated secrets with contents of vault refs in etcd. as i understand this ticket is also about.
> 
> I'm not sure how you've got VSW set up, but we've never seen the kinds of problems you're describing. It sounds like maybe your setup is in need of some tweaking? Other than a few things we've identified with the ecosystem, it works pretty nicely, but the things we've identified are pretty big deals. The things we spoke of above are one of the main problems we've identified. Another one is the inability for VSW ecosystem to update/mutate secrets in running pods when secrets are changed in vault.

I got rid of creating docker secrets via VSW at the time being. We spotted a bottle neck in storage IOPS for 2/3 nodes. 2 of them use a CEPH volume with spinning disks which seemed much to slow for Raft to work properly. We meanwhile switched to SSDs and this made vault much more stable again.

But why secrets ended up non mutated on the system I think is a race condition between our GitOps tool Flux and the mutating webhook. And because vault was not functioning properly the VSW get time outs for the mutation and the non mutated Secret ends up on the cluster as defined by Flux.

I guess instead of parsing ConfigMap or Secret directly, I bank-vaults should introduce 2 CRDs for VaultSecret or VaultConfigMap and define those in GitOps and let the mutating webhook/operator create the actual parsed Secret or ConfigMap so there won't be a race condition between gitops tooling and bank-vaults.

**Comment by notjames** [comment]
we've been discussing getting off banzaicloud products because of lack of support and maintenance. More to come on that.
