### ISSUE TITLE
[vault-operator] add OPERATOR_LOG_LEVEL setting to values for the vault-operator chart

### ISSUE THREAD

**Issue by jkirkham-ratehub** [bank-vaults/bank-vaults#1490]
**Is your feature request related to a problem? Please describe.**
It appears that the vault-operator (as installed by the Helm chart) has hard-coded the log-level to `debug`.  https://github.com/banzaicloud/bank-vaults/blob/1b3a8b7480c061866616a3563838d2214682479d/charts/vault-operator/templates/deployment.yaml#L50-L51
This is producing a lot of unnecessary log data for us.  It would be better to make this configurable.

**Describe the solution you'd like**
Expose OPERATOR_LOG_LEVEL in the values.yaml of the Helm chart for vault-operator so it can be changed as needed by end users.

**Describe alternatives you've considered**
I haven't tried this yet, but it may be possible to use a kustomize overlay to patch the rendered Helm chart with the desired log level.  Though having this as a configurable part of the Helm chart would be easier.

**Comment by SCLogo** [comment]
any update on this?
