### ISSUE TITLE
Fail to restore vault with velero  in another namespace

### ISSUE THREAD

**Issue by liyaka** [bank-vaults/bank-vaults#1494]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
I'm trying to restore from a vault backup created with velero from namespace `dev` into another namespace - `xxx`
I'm using instructions from https://banzaicloud.com/blog/vault-backup-velero/, just creating restore with `--namespace-mappings`
The only thing that seems to be not mapped, since it's not a k8s configuration, but a command flag for bank-vaults container, is:

> - args:
>     - --pre-flight-checks
>     - "true"
>     - --mode
>     - k8s
>     - --k8s-secret-namespace
>     - dev
>     - --k8s-secret-name
>     - vault-unseal-keys
>     - --k8s-secret-labels
>     - app.kubernetes.io/name=vault,vault_cr=vault

you can see that `--k8s-secret-namespace `is still `dev`

**Expected behaviour**:
Restore will work smooth like if i would restore in the oridinal namespace

**Steps to reproduce the bug**:
instructions from https://banzaicloud.com/blog/vault-backup-velero/, just creating restore with `--namespace-mappings`, like
`velero restore create from-dev-to-xxx--from-backup vault-dev-20211213130054 --namespace-mappings dev:xxx`

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.19.13-eks-8df270
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): ghcr.io/banzaicloud/bank-vaults:1.13.1
- Install method (e.g. helm or static manifests): vault operator with helm chart
- Logs from the misbehaving component (and any other relevant logs):
`kubectl logs vault-0 bank-vaults
{"level":"info","msg":"joining leader vault...","time":"2021-12-13T16:26:12Z"}
{"level":"info","msg":"vault metrics exporter enabled: :9091/metrics","time":"2021-12-13T16:26:12Z"}
{"level":"fatal","msg":"error checking if vault is initialized: unable to get key 'vault-root': error getting secret for key 'vault-root': secrets \"vault-unseal-keys\" is forbidden: User \"system:serviceaccount:xxx:vault\" cannot get resource \"secrets\" in API group \"\" in the namespace \"dev\"","time":"2021-12-13T16:26:12Z"}`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

Is there any solution or workaround for it?

**Comment by liyaka** [comment]
I found a solution/workaround - i restore only pv, pvc and secret in my new namespace and after that i install vault.
I believe it's bug that vault backup can not be fully restored in another namespace

**Comment by bonifaido** [comment]
Hi, I don't think this is an issue with the operator/backup procedure.

What happened here, there was a Vault instance running in namespace A and its RBAC was set up to access Secrets in namespace A.

This instance got backed up, and restored in namespace B, but the RBAC rule content that got restored is still the same, so it allows access to Secrets only in namespace A, so if someone planes to restore Vault in a different namespace the RBAC rules has to be changed manually to be able to access that namespace, that is something the operator can't fix beforehand, since the restore is totally Velero driven.

**Comment by akijakya** [comment]
Issue got answered, closing it.
