### ISSUE TITLE
[vault-secrets-webhook] document podsFailurePolicy

### ISSUE THREAD

**Issue by tony-kerz** [bank-vaults/bank-vaults#1510]
**Is your feature request related to a problem? Please describe.**

i have ongoing issues with race-conditions (amplified with the use of spot instances) where pods come up at a point in time when the web-hook is not present or otherwise not mutating pod secrets, 
so the pod comes up but secret values look like `vault:blah` instead of their required secret values and the pods get into crash-loop-backoff state.

bouncing the pod manually after this condition is discovered typically resolves the problem as the web-hook is non-functional only for a small window of time.

it's possible that `podsFailurePolicy` can mitigate this situation, but it isn't documented [here](https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault-secrets-webhook#configuration),
so i only encountered mention of it in issues discussion threads.

**Describe the solution you'd like**

a description of its behavior (and trade-offs) in the doc would be helpful.

**Additional context**

https://github.com/banzaicloud/bank-vaults/issues/1491

https://github.com/banzaicloud/bank-vaults/issues/983

**Comment by ramizpolic** [comment]
This issue has been resolved in the latest webhook version. Please reopen in affected repo if this issue persists.
