### ISSUE TITLE
Affinity for configurer pod.

### ISSUE THREAD

**Issue by ftpd** [bank-vaults/bank-vaults#1556]
**Is your feature request related to a problem? Please describe.**
Currently the configurer pod has no affinity, so it's deployed 'wherever'. Unfortunately sometimes it deploys on nodes that are designed to be temporary.

**Describe the solution you'd like**
I would like to set affinity for the configurer pod.

**Describe alternatives you've considered**
None - I can't see any other way than adding support for configurer's affinity in the upstream.

**Additional context**
If I understand [the code](https://github.com/banzaicloud/bank-vaults/blob/main/operator/pkg/controller/vault/vault_controller.go#L890-L906) correctly, affinity for configurer is now possible only if HSM is used. It would be nice to have it available without HSM too.

**Comment by bonifaido** [comment]
Yes @ftpd, it is exactly like you say. If you have the willingness to submit a PR for this, that would be awesome, I think we can just reuse the affinity from the Vault pods (so maybe just a few lines of code changes). If not we can introduce a configurer affinity field in the CRD.

**Comment by Ninja-mann** [comment]
> **Is your feature request related to a problem? Please describe.** Currently the configurer pod has no affinity, so it's deployed 'wherever'. Unfortunately sometimes it deploys on nodes that are designed to be temporary.
> 
> **Describe the solution you'd like** I would like to set affinity for the configurer pod.
> 
> **Describe alternatives you've considered** None - I can't see any other way than adding support for configurer's affinity in the upstream.
> 
> **Additional context** If I understand [the code](https://github.com/banzaicloud/bank-vaults/blob/main/operator/pkg/controller/vault/vault_controller.go#L890-L906) correctly, affinity for configurer is now possible only if HSM is used. It would be nice to have it available without HSM too.

**Comment by Ninja-mann** [comment]
#1633
