### ISSUE TITLE
[Contribution] Flat mono color icon for Bank-Vaults

### ISSUE THREAD

**Issue by aabouzaid** [bank-vaults/bank-vaults#1565]
**Is your feature request related to a problem? Please describe.**
I needed an icon for Bank-Vaults for presentation and diagrams but the official logo in the repo is a bit artistic (and probably old).
I saw that there is a [nice new logo](https://banzaicloud.com/img/product/bank-vaults.svg) on the [product page](https://banzaicloud.com/products/bank-vaults/), however, it has a lot of details and will not be clear in a small scale like diagrams and so on.

I've also realized that there is an icon in the [overview diagram](https://banzaicloud.com/docs/bank-vaults/images/bank-vault-overview.png) but to me, the icon looks inconsistent! There are 3 different icons in that diagram (non-flat at the top, flat with circle, flat without circle).

**Describe the solution you'd like**
I've created a flat version based on the image on the [product page](https://banzaicloud.com/products/bank-vaults/) ... and here I share it with you in case you wanted to adopt it officially.

![bank-vaults-icon](https://gist.githubusercontent.com/aabouzaid/13438ddf375ac4367778c8dab6d5e6bf/raw/b0b9a7dee9c2f6d896da3426dcb455d74aded37e/bank-vaults-icon.svg)

I've actually created 2 versions ... one that exactly follows the original logo on the product page which has `rounded corners`.
Also, I've created another version with `sharp corners` which follows the style of [Hashicorp Vault logo](https://www.hashicorp.com/brand#vault) where it has sharp corners and squares inside.

I'm in favour of the one with sharp corners because it's closer to the Vault logo as well as it's rendered better in a small scale like diagrams and so on (well, and it looks cool IMO :grinning:)

That's all :-)

**Comment by aabouzaid** [comment]
@bonifaido if this is not the right place for this please tell me where to post it.

**Comment by bonifaido** [comment]
Hi @aabouzaid ! TBH i have no objections against a new icon, and I agree that it could be more clear, so why not? :)

**Comment by aabouzaid** [comment]
@bonifaido cool, let's do it then :rocket: 

First of all. I did a small survey and found that most of the people like the rounded logo, so let's use it.

Second, I will make a PR to use it. Here are the places where I know it should be used:
- Documentation.
- Main readme file.

Anywhere else?

**Comment by aabouzaid** [comment]
Done in #1571 :heavy_check_mark:
