### ISSUE TITLE
Operator having issue with fluentd configMap 

### ISSUE THREAD

**Issue by cten** [bank-vaults/bank-vaults#1572]
**Describe the bug**:
After upgrading to 1.15.2 the operator now fails with this log message:

```
{"level":"error","ts":1648226356.2325327,"logger":"controller-runtime.manager.controller.vault-controller","msg":"Reconciler error","name":"vault","namespace":"vault","error":"failed to create/update fluentd configmap: ConfigMap \"vault-fluentd-config\" is invalid: data[]: Invalid value: \"\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"}
```

**Expected behaviour**:
New configs applied successfully.

**Steps to reproduce the bug**:
Upgrade to 1.15.2

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.22.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): kOps
- bank-vaults version (e.g. 0.4.17): 1.15.2
- Install method (e.g. helm or static manifests): static manifests
- Logs from the misbehaving component (and any other relevant logs): see above
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
  fluentdConfig: |
    <source>
      @type tail
      format json
      keep_time_key true
      time_format %iso8601
      path /vault/logs/vault.log
      pos_file /vault/logs/vault.log.pos
      tag s3.vault.audit
    </source>
    <match s3.*.*>
      @type s3
      s3_bucket vault-data-phishlabs-infra
      s3_region us-east-1
      path audit-logs/
      time_slice_format %Y%m%d%H
      time_slice_wait 10m
      utc
    </match>
  fluentdEnabled: true
  fluentdImage: 'banzaicloud/fluentd-s3:latest'
```

/kind bug

**Comment by avoidik** [comment]
do you have something in it?

```bash
kubectl get cm vault-fluentd-config -o yaml -n vault
```

**Comment by avoidik** [comment]
yes, the operator should create it, I thought you have created it manually before the deployment

**Comment by revathyr13** [comment]
I am also facing the same issue. The operator is throwing the same error. Any fix for this ?

**Comment by chrism417** [comment]
I finally got this working... I had to set this in the vault instance in the same line as fluentdConfig:

`fluentdConfFile: fluent.conf`
