### ISSUE TITLE
[Question] Deployment through helm chart vs operator

### ISSUE THREAD

**Issue by aelbarkani** [bank-vaults/bank-vaults#1582]
Hi all !

I know that in general operators can simplify some day 2 operations. But in this specific case, what would be the added value of the operator deployment vs the helm chart deployment ?

**Comment by akijakya** [comment]
Better late than never: one of the main values added by the [operator](https://bank-vaults.dev/docs/operator/) is that Vault can be configured dynamically and continuously via a CRD file instead of multiple Helm releases.
