### ISSUE TITLE
Ability to mount secrets as a volume in the container

### ISSUE THREAD

**Issue by ishanjain28** [bank-vaults/bank-vaults#1589]
**Is your feature request related to a problem? Please describe.**
Currently, This project allows mounting secrets in the deployment environment/secrets/configmaps or other CRDs.

I have some secrets that I want to mount as a file in the container. The suggested approach to this has been to,
1. create a configmap or a secret
2. mount that configmap/secret as a volume in the container.

This creates a race condition if you have specified configmap/secret _and_ the deployment in the same file and the changes will be applied at the same time. 

Sometimes, The deployment is updated _before_ the secret and continues to use the old version of secret and there doesn't appear to be a way to specify dependencies between k8s resources.

**Describe the solution you'd like**
Some way to mount a vault secret as a volume directly without involving k8s secrets/configmaps will be really nice. I am not sure how will this work without a custom storage driver? 

**Describe alternatives you've considered**
One possible solution to this is to decouple secret/configmap and deployment configuration into two files. Apply secret/configmap change first, wait for a few seconds and then apply deployment configuration.

**Additional context**
Hashicorp vault's official integration uses a CSI driver to do the same thing. https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver?in=vault/kubernetes#install-the-secrets-store-csi-driver

**Comment by akijakya** [comment]
I think using Bank-Vaults the best practice would be to mount secrets to workloads via [env values](https://bank-vaults.dev/docs/mutating-webhook/configuration/#read-a-value-from-vault) or [annotation](https://bank-vaults.dev/docs/mutating-webhook/configuration/#mount-all-keys). If you'd like to mutate secrets and then mount them to workloads I'd recommend taking a look at the External Secrets operator! 😊
