### ISSUE TITLE
Unable to pull secrets when vault-configurer is down

### ISSUE THREAD

**Issue by LiorLieberman** [bank-vaults/bank-vaults#1603]
**Describe the bug**:
When vault-configurer is down, other pods in the cluster can not pull secrets.
Here is the log from vault pod while the other pods trying to pull secrets and the configurer is not up:

`login unauthorized due to: lookup failed: service account unauthorized; this could mean it has been deleted or recreated with a new token
`

This happens because vault configurer is configuring k8s_auth with `token_reviewer_jwt` of its own (if we aren't set it explicitly) which prevents us using the local **Vault pod** token as reviewer JWT as described [here](https://www.vaultproject.io/docs/auth/kubernetes#use-local-service-account-token-as-the-reviewer-jwt)

https://github.com/banzaicloud/bank-vaults/blob/52cf23528eb30c90c6612d94c046697dcb3f06aa/internal/vault/auth_methods.go#L217-L222

So when the configurer is down, k8s deletes the token used, to configure k8s_auth method so then when Vault k8s auth tries to use the token with the API, it says that token has expired.

The only way to overcome it is to set `kubernetes_host` key and avoid using the default config as you can see here
https://github.com/banzaicloud/bank-vaults/blob/52cf23528eb30c90c6612d94c046697dcb3f06aa/internal/vault/auth_methods.go#L64-L66

**Expected behaviour**:
Pods should be able to pull secrets when configurer is down as well. 
We should not set `kubernetes_host` when running vault on the same cluster.

**Steps to reproduce the bug**:
1 ) Omit `kubernetes_host`, `token_reviewer_jwt` from your kubernetes auth config. 
2) Sync vault configurer 
3) Scale vault configurer replicas to 0
4) Try to pull secrets with k8s_auth

**Additional context**:

**Environment details**:
- Kubernetes version: v1.21.5
- Cloud-provider/provisioner: EKS
- bank-vaults version: 1.15.2

/kind bug

**Comment by msvticket** [comment]
I can verify this problem still exists with the latest versions:

    Kubernetes version: 1.30.2
    Cloud-provider/provisioner: EKS
    bank-vaults version: 1.31.1
    vault: 1.17.1

That token_reviewer_jwt is set by vault configurer means another thing as well that is arguably worse: If vault configuration isn't changed so that vault configurer is run kubernetes authentication with vault will stop working when the token given to vault by vault configurer has expired. On EKS this is after 90 days.
