### ISSUE TITLE
Vault Operator - Allow to change statsd mapping configuration

### ISSUE THREAD

**Issue by avoidik** [bank-vaults/bank-vaults#1623]
**Is your feature request related to a problem? Please describe.**

I want to be able to change statsd configuration

**Describe the solution you'd like**

Expand Vault Operator spec to include another option where I can set custom statsd mapping configuration

**Describe alternatives you've considered**

Use default configuration

**Additional context**

https://github.com/banzaicloud/bank-vaults/blob/main/operator/pkg/controller/vault/vault_controller.go#L1526-L1531

**Comment by akijakya** [comment]
Seems like it got resolved by the linked PR.
