### ISSUE TITLE
What is the highest supported version for upstream Vault?

### ISSUE THREAD

**Issue by ftpd** [bank-vaults/bank-vaults#1673]
Hi!

Sorry for asking such basic question via a GitHub issue, but I'm unable to get Slack invitation since last Friday.

Long story short, in [values.yaml](https://github.com/banzaicloud/bank-vaults/blob/main/charts/vault/values.yaml#L13) the tag of the image called simply 'vault' is set to 1.6.2. Is this the upstream Vault from Hashicorp? If so, why is it so outdated version (the current is 1.11, last supported 1.8 - [source](https://hub.docker.com/_/vault)) and what's the maximum value I can go there?

**Comment by ftpd** [comment]
It seems this version is hardcoded in operator, too.

**Comment by jonwtech** [comment]
I'm using 1.10.5 and it works fine. However if I try to upgrade to 1.11 I hit this issue: https://github.com/banzaicloud/bank-vaults/issues/1649

**Comment by ftpd** [comment]
Hey, thanks for the info.

I've updated to 1.10.5 and got lots of errors about 'context cancelled'. After bumping to 1.12.1, I also can confirm problems from #1649. I'm testing 1.10.8 now, I will update the ticket with the results.

**Comment by ftpd** [comment]
This is the exact 'context cancelled' error message:

```
2022-11-03T14:10:02.667Z [ERROR] core: error during forwarded RPC request: error="rpc error: code = Canceled desc = context canceled"
2022-11-03T14:10:02.667Z [ERROR] core: forward request error: error="error during forwarding RPC request"
```

But it seems everything works, except tons of these in secondary/standby vault instance's logs.

**Comment by ramizpolic** [comment]
At the moment, 1.10 is supported, but we are adding support for higher versions as well
