### ISSUE TITLE
Secret mutation is not working properly

### ISSUE THREAD

**Issue by deepaksinghkhetwal** [bank-vaults/bank-vaults#1678]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
I am trying to mutate the secret. I have stored the value in vault. Value of secret is being correctly fetched but it gets changed to the vault path vault:secret/data/redis#REDIS_PASSWORD after sometime

**Expected behaviour**:
The value of secret should not change

**Steps to reproduce the bug**:
Install Redis helm chart
below should be placed for secret

password: vault:secret/data/redis#REDIS_PASSWORD

**Additional context**:
works fine with pods

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.21
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.14.3
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by kajov** [comment]
If this hasn't been solved for secret k8s file use the VAR encased in curly brackets

`${vault:secret/data/redis#REDIS_PASSWORD}`

**Comment by akijakya** [comment]
Hi @deepaksinghkhetwal, thanks for using Bank-Vaults! I tried to reproduce the issue, installing Redis like this:

```shell
helm install redis oci://registry-1.docker.io/bitnamicharts/redis \
  --set auth.password=vault:secret/data/redis#REDIS_PASSWORD \
  --set secretAnnotations."vault\.security\.banzaicloud\.io/vault-addr"=https://vault.default.svc.cluster.local:8200 \
  --set secretAnnotations."vault\.security\.banzaicloud\.io/vault-tls-secret"=vault-tls
```

But I only see the secret being created, and remaining the same without a problem:

```shell
echo $(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 -d)
3xtr3ms3cr3t
```

I can't think of anything right now that would change the value in the secret back to `vault:secret/data/redis#REDIS_PASSWORD` (in its base64 encoded format), but even if that happens, the webhook should pick it up and inject the secret again.
