### ISSUE TITLE
vault version

### ISSUE THREAD

**Issue by rkoosaar** [bank-vaults/bank-vaults#1717]
Hi, I noticed that hashicorp has released version 1.12.x? 
What version of vault is bank-vaults using?

**Comment by rkoosaar** [comment]
I found https://github.com/banzaicloud/bank-vaults/issues/1673 and https://github.com/banzaicloud/bank-vaults/issues/1649 which are actually helpful

**Comment by rkoosaar** [comment]
I've managed to get it working with - vault:1.10.8 / v1.24.7+k3s1

**Comment by rkoosaar** [comment]
also this combo seems to work: vault:1.11.5 / v1.24.7+k3s1

**Comment by jonwtech** [comment]
@rkoosaar can I ask which storage backend you are using? I have a suspicion https://github.com/banzaicloud/bank-vaults/issues/1649 might be related to storage backend as I get this issue on Vault 1.11 on a cluster with Postgres storage but not on a cluster using Raft storage.

**Comment by rkoosaar** [comment]
@rkoosaar I'm using file storage backend in this test environment. I do plan to switch to raft.
 I've not tried with postgres.

**Comment by squaricdot** [comment]
I'm running 1.11.3 using a raft with bank-vaults 1.16.0 on k8s 1.23.* upgraded from 1.6.0 without problems.

for the iss we configured the issuer in the authentication config uing: `kubectl get --raw=/.well-known/openid-configuration | jq -r .issuer`

**Comment by JrCs** [comment]
Vault >= 1.12.x is not supported actually by banks-vault: new vault clusters can't be initialized.  
The problem is: https://support.hashicorp.com/hc/en-us/articles/10294862912659-Vault-operator-init-cross-version-limitation

**Comment by moustafab** [comment]
> Vault >= 1.12.x is not supported actually by banks-vault: new vault clusters can't be initialized. The problem is: https://support.hashicorp.com/hc/en-us/articles/10294862912659-Vault-operator-init-cross-version-limitation

I believe https://github.com/banzaicloud/bank-vaults/pull/1755 will fix this issue

**Comment by mrala** [comment]
It would be nice to more visibly document the latest version of Vault that is supported, especially if it's not reflected in the [deploy examples](https://github.com/banzaicloud/bank-vaults/tree/main/operator/deploy).

**Comment by bonifaido** [comment]
Thank you very much for the comments, we are working on a documentation and also on testing together current Vault versions with the operator. The plan is to document all limitations, and also the policy that is that we are willing to support all Vault versions on a Best effort basis, focusing on the last and the last Vault 3 versions.

**Comment by rkoosaar** [comment]
@bonifaido What versions of vault does the 1.19.0 support? If I was to upgrade to vault 1.12.3 would that work now?
