### ISSUE TITLE
Not able to see vault-configurer pod when deploying Vault from banzai cloud

### ISSUE THREAD

**Issue by mustufa5689** [bank-vaults/bank-vaults#1807]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
Not able to get the bank-vault container creating the unseal keys.

**Expected behaviour**:
Vault when deployed using banzai cloud as kind: vault, should able to create the un-seal keys.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.24
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.18.0
- Install method (e.g. helm or static manifests): helm, Argocd way.
- Logs from the misbehaving component (and any other relevant logs):

{"level":"info","msg":"vault is sealed, unsealing","time":"2023-02-23T16:13:29Z"}
{"level":"error","msg":"error unsealing vault: unable to get key 'vault-unseal-0': error getting secret for key 'vault-unseal-0': secrets \"vault-unseal-keys\" not found","time":"2023-02-23T16:13:29Z"}
{"level":"info","msg":"vault is sealed, unsealing","time":"2023-02-23T16:13:34Z"}
{"level":"error","msg":"error unsealing vault: unable to get key 'vault-unseal-0': error getting secret for key 'vault-unseal-0': secrets \"vault-unseal-keys\" not found","time":"2023-02-23T16:13:34Z"}
{"level":"info","msg":"vault is sealed, unsealing","time":"2023-02-23T16:13:39Z"}

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by mustufa5689** [comment]
Hello Team,

Any updates.

**Comment by akijakya** [comment]
Hi @mustufa5689, thanks for using Bank-Vaults! Could you please elaborate on how did you try to install it (which Helm chart, what configuration)? Thanks!

**Comment by mustufa5689** [comment]
Hello,

Steps I followed.

1. install the operator using the helm chart in vault-operator ns.
2. Customised the Cr.yaml file to use dynamodb as backend for vault data.
3. Installed [2], with kubectl apply along with rbac.yaml.
4. Unseal keys not generated now.

note:- keys were generated before the first attempt but after deleting the keys and redeploying in same ns doesn’t help.

**Comment by mustufa5689** [comment]
Please expedite as we wanna use the vault in production env

**Comment by mustufa5689** [comment]
Hello Team,

Any help would be appreciated.
Thanks,
Mustufa.

**Comment by akijakya** [comment]
Hi, sorry for the delay. Could you please share your cr.yaml without the sensitive data?

**Comment by ramizpolic** [comment]
Hi @mustufa5689, apologies for the delay, please feel free to resubmit the issue if you did not manage to resolve it yet. It is a bit difficult to triange an issue without steps to reproduce. Thanks for understanding, we hope to respond more quickly moving forward. Cheers!
