### ISSUE TITLE
This is the continuation of : https://github.com/banzaicloud/bank-vaults/issues/1722

### ISSUE THREAD

**Issue by signinred** [bank-vaults/bank-vaults#1819]
We have upgraded the vault image to 1.13.1 but we are not able to insert the flag "iss validation" 

We are able to modify the existing key values but not able to add the new values. Could you please suggest. 

`vault kv put auth/kubernetes/config kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR} kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt disable_iss_validation=true`

`/ # vault kv get -format=json auth/kubernetes/config
{
  "request_id": "674646467-3a37-e36b-d262-9265c068c1af",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "issuer": "",
    "kubernetes_ca_cert": "-----BEGIN CERTIFICATE-----\nMIIDjDCCAnSgAwIBAgIUTS25upWdU6QcWkHW1fLg8zjGPxUwDQYJKoZIhvcNAQEL\nBQAwXjELMAkGA1UEBhMCVVMxDjAMBgNVBAgTBVRleGFzMQ8wDQYDVQQHEwZBdXN0\naW4xDzANBgNVBAoTBk9yYWNsZTEMMAoGA1UECxMDT0RYMQ8wDQYDVQQDEwZLOFMg\\\nY2xlMQwwCgYDVQQLEwNPRFgxDzANBgNVBAMTBks4UyBDQTCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBALnkheJYL8sbfbx2UEZGHhAdG2sDDrqY5vCCvn77\n8JvUsJzMRdY2mWM+JxepmOzmnlCDpJlaDPbcl+J1kSYTkyx8Tclz/0dgv7Nosv9e\nmC5AgwhIe7sO4xdOpL90/ixKmt/+bkjhzdkjhkjhsjkhdkjhzkdhkhzd\nQyWAT+zdlkhlkdzkljzkjjzlzjklzd\nRL/SA0S1mjl7umswpt1BdrjFyHDs+SrD/WK3m9+uOxvaerUT0v7rjnElvE7DXZEM\na2ffHbqdR0df7tXgXKSt9fLjSkpB5qkmVUldx+10Fc/M6QECAwEAAaNCMEAwDgYD\zdl/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOzvai7hXPD0\n/8D+huX/5T1SIRMbMA0GCSqGSIb3DQEBCwUAA4IBAQALbI7xwG/yJZdv584xD9ya\nvbkOzfLd7QLR438VJllVwAm5tyhBmTxl8jct2UAlYqZjMlGqo+/9nHcQC4nz5hFJ\n9J/zdlkjzkkzdjkzljkzd+quBLcpeU/OExcdts76B1kHlLAiaX\nWm/Z9Tz6nxzNjj31LiMXYUCFBb8YxfbrZggNlV53+oKzcdsopI17Lj9auLg8ubeh\n5RS3presd1EJlF1PFQuyVDYIy/zdlkjlkzjzjzkljzlkd\n0OAe6jZeiEIyQzNfTWOXkFqfGGQRntdKv8/7q40EHrErr/9K58lcCaebISTU6LDe\n-----END CERTIFICATE-----\n",
    "kubernetes_host": "https://10.2.2.2",
    "pem_keys": []
  },
  "warnings": null
}`

Kuberentes cluster version: v1.21.5

###################################################################

> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:

**Expected behaviour**:
A concise description of what you expected to happen.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- bank-vaults version (e.g. 0.4.17):
- Install method (e.g. helm or static manifests):
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by akijakya** [comment]
Hi @signinred, sorry for replying this late.
Could you please specify the Vault image version, and Bank-Vaults version you are using? If you are still using Vault version `1.2.3` that might be an issue because this config did not exist back then. Otherwise I did a quick test locally and the field `disable_iss_validation` (and also `disable_local_ca_jwt`) was present and modifiable each time using various combination of Vault (1.6.2 and newer) and Bank-Vaults (1.13.1 and newer) versions. As far as I can tell, Bank-Vaults doesn't even touch this configuration, this field comes with Vault by default, so I am not sure what went wrong if not because of old version - can you provide more information on how to reproduce this issue? Thanks!

**Comment by akijakya** [comment]
This issue seems to be stale so closing it, if @signinred you still have questions, feel free to open again or ask them in a separate issue/thread!
