### ISSUE TITLE
Inject All secrets from Vault to ConfigMap

### ISSUE THREAD

**Issue by chopanovv** [bank-vaults/bank-vaults#1827]
i dont find any annatations for injecting all secrets to configMap! Because lets assume i have got millions of values in vault and want to inject all secrets to configMap.

**Comment by akijakya** [comment]
Hi @chopanovv, thanks for using Bank-Vaults, also sorry for the late response! What you suggest here doesn't sound like a good idea to me, this project aims to use the most secure ways to use Vault secrets inside your Kubernetes cluster and dumping all/a lot of them into a configmap is not among them. If your main use case is to have all/parts of your Vault secrets within your cluster I'd suggest you to take a look at other projects, like [secrets-manager](https://github.com/tuenti/secrets-manager)! 🙂

**Comment by akijakya** [comment]
This issue seems stale so closing it, but @chopanovv if you still have questions, feel free to ask them.
