### ISSUE TITLE
Webhook: empty secret-version-hash annotation

### ISSUE THREAD

**Issue by lgecse** [bank-vaults/bank-vaults#1853]
Webhook: when feature is enabled on the resource - alpha.vault.security.banzaicloud.io/reload-on-secret-change == true
, it will empty the secret-version-hash annotation. 

Annotation name:

alpha.vault.security.banzaicloud.io/secret-version-hash

**Comment by akijakya** [comment]
Specification for this feature has been changed and its progress is tracked in another project.
