### ISSUE TITLE
Operator: update secret-version-hash

### ISSUE THREAD

**Issue by lgecse** [bank-vaults/bank-vaults#1854]
Compares stored, calculated secret-version-hash with the one found on the resource. If different, updates it to the latest. 

Changes on the annotation on resources will result K8s restarting the resource.

Only when resource has annotation alpha.vault.security.banzaicloud.io/reload-on-secret-change == true

**Comment by akijakya** [comment]
Specification for this feature has been changed and its progress is tracked in another project.
