### ISSUE TITLE
error checking if vault is sealed: error checking status: context deadline exceeded

### ISSUE THREAD

**Issue by jochen-schreiber** [bank-vaults/bank-vaults#2007]
Wondering if anybody has ever encountered this:

We are running vault in an HA setup with dynamodb and 3 pods:

```
NAME                                                              READY   STATUS    RESTARTS        AGE
asms-operator-vault-operator-5f4645d8c8-x6m2v                     2/2     Running   2 (2d1h ago)    2d1h
asms-webhook-vault-secrets-webhook-79c4bc6cfc-484kd               2/2     Running   0               2d1h
asms-webhook-vault-secrets-webhook-79c4bc6cfc-9rf9t               2/2     Running   0               2d1h
vault-0                                                           3/3     Running   1 (14d ago)     14d
vault-1                                                           3/3     Running   1 (14d ago)     14d
vault-2                                                           3/3     Running   1 (6d15h ago)   6d15h
vault-configurer-68fc594985-wbf56                                 2/2     Running   0               9d
```

We had like an outage situation (where 403 from other services are reported) and saw the following error in the **bank-vaults** container of the vault pod that is the leader:

```
{"level":"info","msg":"initializing vault...","time":"2023-06-20T22:32:35Z"}
{"level":"info","msg":"vault metrics exporter enabled: :9091/metrics","time":"2023-06-20T22:32:35Z"}
{"level":"info","msg":"vault is already initialized","time":"2023-06-20T22:32:39Z"}
{"level":"info","msg":"vault is sealed, unsealing","time":"2023-06-20T22:32:39Z"}
{"level":"info","msg":"successfully unsealed vault","time":"2023-06-20T22:32:40Z"}
{"level":"error","msg":"error checking if vault is sealed: error checking status: context deadline exceeded","time":"2023-06-29T22:48:42Z"}
{"level":"error","msg":"error checking if vault is sealed: error checking status: context deadline exceeded","time":"2023-06-29T22:49:12Z"}
{"level":"error","msg":"error checking if vault is sealed: error checking status: context deadline exceeded","time":"2023-06-29T22:49:29Z"}
...
{"level":"error","msg":"error checking if vault is sealed: error checking status: context deadline exceeded","time":"2023-06-29T22:58:27Z"}
{"level":"error","msg":"error checking if vault is sealed: error checking status: context deadline exceeded","time":"2023-06-29T22:58:29Z"}
{"level":"error","msg":"error checking if vault is sealed: error checking status: context deadline exceeded","time":"2023-06-29T22:59:12Z"}
```

This automatically stopped then and one of the standby pods (vault-2) was restarted for whatever reasons. After that vault was again operational and service teams were able to operate with vault. 

Not sure what else i can provide as logs as there is basically nothing else which is suspicious at that time. Please let me know if there is any other information you need to know.

Here are a few version and configuration information:

**vault status of vault-1 pod - which is the leader**
```
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.7
Build Date      2023-06-06T18:12:20Z
Storage Type    dynamodb
Cluster Name    vault-cluster-186e8910
Cluster ID      ebfb56e5-e4d2-bbbc-5b53-c10185cd6f26
HA Enabled      true
HA Cluster      https://vault-1:8201
HA Mode         active
Active Since    2023-06-20T22:32:41.128313768Z
```

**bank-vaults version**: 1.16.0

**Comment by jochen-schreiber** [comment]
As far as i can see the following code is being executed and throws the error:

https://github.com/banzaicloud/bank-vaults/blob/18abb6cb610aa163fb9bad23494d2a13d466554e/cmd/bank-vaults/unseal.go#L144C21-L144C21

When i go back all the call hierarchy it seems this is the api function that is being used to executed the HTTP call to check the vault seal status of the vault instances:

https://github.com/hashicorp/vault/blob/main/api/sys_seal.go#L15C4-L15C4

With "context deadline exceeded" message it could mean that the HTTP call takes longer then excepted. Is there something configurable to support "longer" taking requests?

**Comment by sagikazarmark** [comment]
It seems to me there is a default of 60 seconds as timeout in the client: https://github.com/hashicorp/vault/blob/main/api/client.go#L253

Increasing the timeout beyond that doesn't sound particularly "healthy" to me.

I'm inclined to say there may be some networking problem in your cluster.

I believe you should be able to increase that timeout by setting the `VAULT_CLIENT_TIMEOUT` env var to something more than 60 seconds (it accepts Go duration string).

**Comment by jochen-schreiber** [comment]
@sagikazarmark the timeout is now set to 180 seconds. The issue recently occurred in one of our environments and i can still see the message each minute so i guess it won't worked.

Right now we are rolling out bank-vaults version 1.19.0 (we had 1.16.0 before) in combination with vault version 1.14.1.
Hopefully this update will prevent this context deadline exceeded messages.

Just want to quickly get your opinion what to check on the kubernetes cluster. Once the issue occurs i can still connect to vault and read/write secrets by using the webhook. So vault itself is good at that point. Accepts requests on the incoming addresses and so on. What can we check for this kind of issue? Do you have any idea?
