### ISSUE TITLE
use hashicorp/vault image as _/vault is deprecated

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/bank-vaults#2040]
See bank-vaults/vault-secrets-webhook#65

**Comment by akijakya** [comment]
Also the latest 4 versions are: 1.11.12, 1.12.8, 1.13.4, 1.14.0

**Comment by sagikazarmark** [comment]
Feel free to take a lead on upgrading versions, but please do so in all projects. (You can use a single draft item on the project board to track this activity)
