### ISSUE TITLE
Latest docker images are missing in dockerhub

### ISSUE THREAD

**Issue by lingxiankong** [bank-vaults/bank-vaults#2099]
**Describe the bug**:
Latest docker images (e.g. 1.20.4) are missing in dockerhub, https://hub.docker.com/r/banzaicloud/bank-vaults/tags, maybe the images are pushed to somewhere else but I didn't find such information from the documents.

**Expected behaviour**:
I am keen to pull the bank-vaults docker image from dockerhub (which is accessible already internally)

**Steps to reproduce the bug**:
Check https://hub.docker.com/r/banzaicloud/bank-vaults/tags

**Additional context**:
N/A

**Environment details**:
N/A

/kind bug

**Comment by tanmay-pnaik** [comment]
Latest images are submitted at ghcr.io/bank-vaults/bank-vaults
See here: https://github.com/bank-vaults/vault-helm-chart/blob/main/vault/values.yaml#L252

**Comment by tanmay-pnaik** [comment]
FYI: https://github.com/orgs/bank-vaults/discussions/1878
