### ISSUE TITLE
vault rekey and rotate - is it supported?

### ISSUE THREAD

**Issue by raoofm** [bank-vaults/bank-vaults#456]
**Is your feature request related to a problem? Please describe.**
vault rekey and rotate operations are part of vault operator commands. Though this can be done manually but it requires the human to actually fetch the keys from s3 and decrypt it using kms key and use it to rekey. 

**Describe the solution you'd like**
I think the above exposes the keys to a human and ideally should be able to trigger this say via vault CR in an automated way.

**Describe alternatives you've considered**
none

**Additional context**
https://www.vaultproject.io/docs/internals/rotation.html

**Comment by bonifaido** [comment]
No this is not yet supported but could be a valuable addition, but it is not trivial to implement, so we need to think about it first how to do this correctly.

**Comment by raoofm** [comment]
@bonifaido rotate is pretty straightforward as it doesn't require the shared keys. It will just rotate the backend key used for encryption. rekey requires all the shares to be present and might require some work. Can you share your concerns when you say it is not trivial so that we can take the discussion forward. I think it is a good addition as most organization might have a key rotation policy.

**Comment by bonifaido** [comment]
My concerns are basically time-related only, namely that we don't have time currently to implement this, but I still think this a valid and valuable feature.

**Comment by raoofm** [comment]
thanks @bonifaido fair enough

**Comment by ramizpolic** [comment]
Closing this as not relevant anymore. Please reopen if still needed.
