### ISSUE TITLE
Issues and roadblocks trying to expose Vault via Ingress on GKE

### ISSUE THREAD

**Issue by fraenkel** [bank-vaults/bank-vaults#565]
My goal was to stand up Vault on GKE for both internal and external consumption.
I did figure out a solution that works although I uncovered some issues and limitations along the way that I would like to describe.

The final solution was to do the simplest solution and just let a default vault get stood up with an Ingress with a LetsEncrypt certificate to the api-port on Vault.

- Attempt 1 - Use the generated certificate on the Ingress
The upside/downside is that it requires the CA to be handed to all clients.
**Issue:** The externalTrafficPolicy is set to Cluster. Since we need NodePorts, my preferred setting would be Local.
**Issue:** This doesn't work because there is no way to inject additional DNS SANs in the certificate to allow inbound requests to match.
A negative is that it wouldn't work well for browsers if implemented.
If I wanted to truly lock it down with mutual TLS, Ingress wouldn't work because there would be no way to go from the LB -> Vault.

- Attempt 2 - Use a LoadBalancer on the Service
This has the same issue as above. The certificate does not have the DNS name included in the Certificate.

- Attempt 3 - Disable TLS
To simplify the setup, I wanted to drop TLS and just protect it at the LoadBalancer using LetsEncrypt.
**Issue:** The _DisableTLS_ checks are incorrect. The Vault config for Listeners are a list of maps. The code assumes it's a single map. I never got this to work.

- Attempt 4 - Add an additional listener port
I created an additional TLS port with my LetsEncrypt certificate and exposed it on the Service
**Issue:** The service annotation _cloud.google.com/app-protocols_ is hard coded and doesn't reflect the additional ports.
**Issue:** Cannot override the healthcheck ports. GKE Ingress needs to invoke the liveness probe. If the backend port matches in the Ingress and the health-check the correct path is used. When they differ, it will use / which always fails.

**Issue:** No way to disable the statsd-exporter. We happen to have a statsd receiver on every node, so its unneeded. The prometheus annotations can be overridden  so that is less of an issue.

**Comment by primeroz** [comment]
I run successfully a setup similar to your attempt 4 based on the example from https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-customports.yaml 

* the listener on port 8300 is my public endpoint , it uses a letsencrypt public certificate , it is exposed using the _haproxy ingress_ as a TCP pool on the same DNS name registered on the letsencrypt certificate SAN. The HAPROXY listener is exposed as loadbalancer type which is then balanced by a TCP load balancer from google. 
  This way i get e2e with valid certificates encryption on the public side
* on port 8200 is the internal listener , using https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml#L81 i distribute the CA into all namespaces so any workload can validate the cert on the internal listener

I don't have any issue with it on GKE, it has been running in production for a few months already. 
Most of my vault clients are actually from other kubernetes clusters and from on-prem so 90% of my traffic is external through the TCP Loadbalancers all the way to vault 

Also Statsd can be disabled by setting statsdDisabled: true , see https://github.com/banzaicloud/bank-vaults/blob/0c3dea2b785e56179b71ed58580d2f84140e9b11/operator/deploy/cr-prometheus.yaml#L16 and https://github.com/banzaicloud/bank-vaults/blob/6670d4c7b6a7ec3b4d20afe1a3dc2e0ff40f8635/docs/mutating-webhook/howto-ct-prom.md

**Comment by fraenkel** [comment]
Your key difference is that you are using haproxy and not the GCE Ingress which places requirements on how healthcheck works.

Combining Attempt 2 and 4 is probably the best approach given the Ingress doesn't provide much value. What I dislike is that the LB is for all ports not just 8300. Or with a slight modification, I create a separate Service which is configured just with 8300 and my externalTrafficPolicy.

Thanks for the _statsdDisabled_.

**Comment by primeroz** [comment]
I use the ingress so that I can share a single lb for all my inbound traffic and differentiate between vault and other services with sni while having a full e2e encryption from client to vault with no Google side ssl termination. 
but I see your point if you only need to expose vault is quite useless.

If you get a working configuration and would not mind writing a quick doc about it to contribute that would be great !

Also, for any other question, I really recommend to use slack over GitHub issues, you will get answers very quickly.

**Comment by bonifaido** [comment]
Hi @fraenkel,

> Issue: The service annotation cloud.google.com/app-protocols is hard coded and doesn't reflect the additional ports.

> Issue: Cannot override the healthcheck ports. GKE Ingress needs to invoke the liveness probe. If the backend port matches in the Ingress and the health-check the correct path is used. When they differ, it will use / which always fails.

Fixing these make sense! Would that fix and the ability of adding more SANs to the cert through the CR solve most of your issues?

**Comment by fraenkel** [comment]
Yes, those three provide the ability to use the generated certificate or add your own on a separate listener and expose it via Ingress or a LoadBalancer.

**Comment by bonifaido** [comment]
One comment, ...on GKE, since on non-GKE clusters it is already possible.

**Comment by fraenkel** [comment]
I think also the externalTrafficPolicy would be a good one. Just being able to change it would be good enough.

**Comment by bonifaido** [comment]
Hi @fraenkel, I'm up to fix this, here is an attempt which is not complete yet: https://github.com/banzaicloud/bank-vaults/pull/569

Could you please help me out and try this out on your GKE cluster?

You can build an operator image with `make docker-operator`

**Comment by fraenkel** [comment]
Sure, which features do you want me to test? The extra certs and disable tls?

**Comment by bonifaido** [comment]
Yes, extra certs is there, you can pass in custom service spec as well and multiple listeners are exposed in the service.

**Comment by ramizpolic** [comment]
not relevant anymore, please reopen if there are any leftover issues to address
