### ISSUE TITLE
[vault-secrets-webhook] Make default vault role setting configurable

### ISSUE THREAD

**Issue by javanthropus** [bank-vaults/bank-vaults#954]
**Is your feature request related to a problem? Please describe.**
Our users currently need to set the vault role for their pod explicitly even though it should always be *namespace_serviceaccount* in our scenarios.  We have been able to define defaults for all of the other settings we need so that our users do not need to worry about them, but not this one since the default is simply the serviceaccount name at this time.  We want to ensure uniqueness of role names across namespaces and serviceaccounts.

**Describe the solution you'd like**
We would like to be able to define the vault role setting for a pod with a default of the form *namespace_serviceaccount*, where namespace is the namespace of the pod and serviceaccount is the serviceaccount the pod is configured to use.  Being able to supply a template for the vault role in the settings for the webhook would grant sufficient flexibility.

We suggest allowing the `VAULT_ROLE` environment variable of the webhook to be set to something like `{{ .namespace }}_{{ .serviceAccount }}` as a template would give us what we need while also allowing its default value to implicitly be `{{ .serviceAccount }}` to preserve backward compatibility.

**Describe alternatives you've considered**
We are currently using the explicit method, but this is additional toil for our users which can be overlooked or incorrectly set, leading to errors that our users must investigate.  We cannot use the current default because it is set to only the name of the serviceaccount for the pod which could be replicated in another namespace and need to remain separate.  Including the namespace in the role name allows for roles to be used that distinguish between the different serviceaccounts.

**Additional context**
None.

**Comment by bonifaido** [comment]
Hi @javanthropus, good idea, I'm happy to have something like this in webhook instead of just the `{{.serviceAccount}}`. I can imagine some go templating pattern, that could be provided to the webhook to create the role name. Are you about to submit a PR for this, that could probably speed up the process?

**Comment by javanthropus** [comment]
Sadly, I'm not a golang developer, so this would take a significant amount of time for me to attempt.  I can raise this issue with others at my company though and see if any of them are able to provide a PR.

**Comment by csatib02** [comment]
Completed in: https://github.com/bank-vaults/bank-vaults/pull/1870
