### ISSUE TITLE
[vault-secrets-webhook] Allow using external ServiceAccount for webhook, or at least choosing the SA name

### ISSUE THREAD

**Issue by kodachimaru** [bank-vaults/bank-vaults#964]
**Is your feature request related to a problem? Please describe.**

When we want to use the Kube Secret mutation feature, we need to map in Vault the webhook's ServiceAccount name to a Vault Role that can read the allowed secrets for the webhook instance.
Said mapping can be done by namespace, SA name or (namespace + SA name).
https://www.vaultproject.io/docs/auth/kubernetes#configuration
("3- Create a named role")

When you want to use the SA name in the mapping, you'd rather deploy the webhook chart being able to specify that SA name, so that it doesn't change because of chart implementation details. Also, you may want to reuse an already existing SA ("external SA") for the webhook instead of the chart creating its own one.

Currently the SA name is set by using the Helm template definition "vault-secrets-webhook.fullname"
https://github.com/banzaicloud/bank-vaults/blob/chart/vault-secrets-webhook/1.0.1/charts/vault-secrets-webhook/templates/webhook-deployment.yaml#L33
https://github.com/banzaicloud/bank-vaults/blob/chart/vault-secrets-webhook/1.0.1/charts/vault-secrets-webhook/templates/_helpers.tpl#L14

There's no way to tell the chart to use an external SA, and no way to name explicitly the chart's own SA. This means that:

1. We have to use forcibly the chart's own webhook SA
1. If we want to at least enforce a name on the webhook SA we have to resort to override the "fullNameOverride" input value, which we may not need/want if we could just choose the SA name.

**Describe the solution you'd like**

I'd like to have 2 new optional input values:

- serviceAccount.create: true
- serviceAccount.name: ""

The default values respect the current chart behaviour: A custom SA will be created, and (given that the name is empty), a custom name will be chosen using the template definition "vault-secrets-webhook.fullname"

If serviceAccount.create==false, the SA won't be created, but expected to be there before the webhook chart deployment. In this case, the serviceAccount.name will be mandatory. 

**Describe alternatives you've considered**

None that I can think of.

**Additional context**

We have several product teams with each one living in its own namespace, and each product  must keep access only to its own secrets.
We are deploying a Helm release of the webhook for each product ns.
We are using Kube Secret mutation, so we need to map the webhook SA's to the Vault Roles carefully.
The naming conventions we use for naming the Helm releases we deploy are changing because of the application of new technical guidelines in the company.

**Comment by bonifaido** [comment]
I absolutely agree and like this functionality @kodachimaru, if you could send a PR for this we would be glad to review and accept it. 👍

**Comment by csatib02** [comment]
Fixed: https://github.com/bank-vaults/bank-vaults/pull/1401/files
