### ISSUE TITLE
[vault-secrets-webhook] Secrets not injected if container image initially fails to pull

### ISSUE THREAD

**Issue by cablespaghetti** [bank-vaults/bank-vaults#983]
**Describe the bug**:

If a Pod starts up with a container image which hasn't been pushed yet, it never gets any secrets injected.
```
time="2020-05-14T15:00:26Z" level=info msg="trying to request AWS credentials for ECR registry https://<redacted>.dkr.ecr.us-east-1.amazonaws.com"
time="2020-05-14T15:00:26Z" level=info msg="Using cached AWS ECR Token for registry https://<redacted>.dkr.ecr.us-east-1.amazonaws.com"
time="2020-05-14T15:00:26Z" level=info msg="got AWS credentials for ecr registry https://<redacted>.dkr.ecr.us-east-1.amazonaws.com"
time="2020-05-14T15:00:26Z" level=info msg="I'm using registry https://<redacted>.dkr.ecr.us-east-1.amazonaws.com"
2020/05/14 15:00:26 registry.manifest.get url=https://<redacted>.dkr.ecr.us-east-1.amazonaws.com/v2/contentrepo/manifests/snapshot-200514-155710-0290 repository=contentrepo reference=snapshot-200514-155710-0290
time="2020-05-14T15:00:26Z" level=error msg="admission webhook error: cannot download manifest for image: Get \"https://<redacted>.dkr.ecr.us-east-1.amazonaws.com/v2/contentrepo/manifests/snapshot-200514-155710-0290\": http: non-successful response (status=404 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"MANIFEST_UNKNOWN\\\",\\\"message\\\":\\\"Requested image not found\\\"}]}\\n\")" app=vault-secrets-webhook
```

When the image is pushed and the container successfully starts up it ends up in a CrashLoopBackOff because the secret never gets injected:
```
java.sql.SQLException: Access denied for user 'vault:secret/data/database/content_repo#username'@'172.31.60.240' (using password: YES)
```
This is a bit of a weird situation admittedly, but it's quite common in our environments for developers to deploy things before the Docker push of the actual application has completed, and I feel like this a situation which should resolve itself.

This could also occur if there is a temporary outage of our registry or if there is some other delay/transient error pulling the container image, and it only recovers if I manually delete the pods affected.

**Expected behaviour**:
The Pod to wait until vault-secret-webhook has mutated it before starting up, after the container image is present in the registry.

**Steps to reproduce the bug**:
Configure a Pod with a container image which doesn't yet exist, then push it to the registry and watch it start but fail to get any secrets injected.

**Environment details**:
- Kubernetes version: v1.15.11-eks-af3caf
- Cloud-provider/provisioner: EKS
- bank-vaults version: master (f588eb8)
- Install method (e.g. helm or static manifests): Helm

/kind bug

**Comment by cablespaghetti** [comment]
This might be as simple as setting the `failurePolicy` for the webhook configuration to `Fail` so the Pod isn't allowed to create.

**Comment by cablespaghetti** [comment]
This is helpfully a parameter in the Helm chart and setting it to Fail does indeed fix the problem. Could I suggest that this is the default?

`podsFailurePolicy: Fail`

**Comment by bonifaido** [comment]
This is not `podsFailurePolicy: Fail` by default because some users had different issues with it, for example some pods can run even if the secret is not available. Initially, it was on by default. Maybe we should pinpoint this out in the docs better.

**Comment by cablespaghetti** [comment]
Just had a fun issue with this. We started scaling one of our dev clusters down to 0 nodes overnight and because this was set to Fail, and of course the webhook pods weren't running, nothing at all could start until I changed it to ignore :laughing:

**Comment by bonifaido** [comment]
Yes, this is a cath-22 situation in this case :)

**Comment by csatib02** [comment]
Seems resolved to me. :D
